name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build-matrix:
    name: Build Matrix
    strategy:
      fail-fast: false # makes for easier debugging across builds
      matrix:
        os: [ macos-14 ] # potentially add additional os'
        preset: [debug, release]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute Cache Key
        id: llvm-version
        run: echo "cache_key=$(brew info --json=v2 llvm | jq -r '.formulae[0].versions.stable')" >> $GITHUB_OUTPUT

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v5
        with:
          path: |
            /opt/homebrew/Cellar/llvm/${{ steps.llvm-version.outputs.cache_key }}/
            /opt/homebrew/opt/llvm

          key: ${{ runner.os }}-llvm-${{ steps.llvm-version.outputs.cache_key }}


      - name: Install LLVM Deps
        run: brew install $(brew deps llvm) --formula

      - name: Install LLVM
        if: ${{ steps.cache-llvm.outputs.cache-hit != 'true' }}
        run: brew install llvm

      - name: Configure
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build build/${{ matrix.preset }}

      - name: Run Tests
        run: ctest --preset ${{ matrix.preset }}


  lint:
    name: Linter (Ubuntu v.24.04)
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clang Format
        run: git ls-files -z '*.cpp' '*.h' '*.hpp' | xargs -0 clang-format --dry-run --Werror
